#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "chassis1.h"
void updateMotors() {
  motor[motorD] = LF; //now we can reference LF as motor D
  motor[motorE] = RF; //RF is E
  motor[motorF] = LR; //LR is F
  motor[motorG] = RR; //RR is G
}

task main() {
  bMotorReflected[motorE] = true; //flips the motor
  bMotorReflected[motorG] = true; //flips the motor
  LF = 100;  //set each of our motors to travel forward at full speed for three seconds.
  RF = 100;  //set each of our motors to travel forward at full speed for three seconds.
  RR = 100;  //set each of our motors to travel forward at full speed for three seconds.
  LR = 100;  //set each of our motors to travel forward at full speed for three seconds.
  updateMotors(); //calls our update function
  wait1Msec(3000); //waits 3 seconds
  LF = -100;  //set each of our motors to travel reverse at full speed for three seconds.
  RF = -100;  //set each of our motors to travel forward at full speed for three seconds.
  RR = -100;  //set each of our motors to travel forward at full speed for three seconds.
  LR = -100;  //set each of our motors to travel forward at full speed for three seconds.
  updateMotors(); //calls our update function
  wait1Msec(3000); //waits 3 seconds
}
