#pragma config(Motor,  motorA,          motorA,        tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  for(int i = 100; i>0; i--) //runs the motor down from top speed
  {
    int FR = i; //sets our new variable to equal i
    wait1Msec(100); //waits 100 milliseconds
    motor[motorA] = FR; //actually tells the motor to run
  }
  for(int i = 0; i<100; i++) //runs the motor back up to top speed
  {
    int FR = i;
    wait1Msec(100);
    motor[motorA] = FR;
  }
}
